version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multitenant_db
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./resources/script.sql:/docker-entrypoint-initdb.d/1-example-multitenant.sql
    expose:
      - "5432"

volumes:
  postgresdata:
